package db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.quitter.quitter.dao.TanWeiInfo;
import com.quitter.quitter.dao.DefinediInfo;

import db.TanWeiInfoDao;
import db.DefinediInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tanWeiInfoDaoConfig;
    private final DaoConfig definediInfoDaoConfig;

    private final TanWeiInfoDao tanWeiInfoDao;
    private final DefinediInfoDao definediInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tanWeiInfoDaoConfig = daoConfigMap.get(TanWeiInfoDao.class).clone();
        tanWeiInfoDaoConfig.initIdentityScope(type);

        definediInfoDaoConfig = daoConfigMap.get(DefinediInfoDao.class).clone();
        definediInfoDaoConfig.initIdentityScope(type);

        tanWeiInfoDao = new TanWeiInfoDao(tanWeiInfoDaoConfig, this);
        definediInfoDao = new DefinediInfoDao(definediInfoDaoConfig, this);

        registerDao(TanWeiInfo.class, tanWeiInfoDao);
        registerDao(DefinediInfo.class, definediInfoDao);
    }
    
    public void clear() {
        tanWeiInfoDaoConfig.clearIdentityScope();
        definediInfoDaoConfig.clearIdentityScope();
    }

    public TanWeiInfoDao getTanWeiInfoDao() {
        return tanWeiInfoDao;
    }

    public DefinediInfoDao getDefinediInfoDao() {
        return definediInfoDao;
    }

}
