package db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.quitter.quitter.dao.DefinediInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEFINEDI_INFO".
*/
public class DefinediInfoDao extends AbstractDao<DefinediInfo, String> {

    public static final String TABLENAME = "DEFINEDI_INFO";

    /**
     * Properties of entity DefinediInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Defined_List = new Property(0, byte[].class, "defined_List", false, "DEFINED__LIST");
        public final static Property Id = new Property(1, String.class, "id", true, "ID");
    }


    public DefinediInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DefinediInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEFINEDI_INFO\" (" + //
                "\"DEFINED__LIST\" BLOB," + // 0: defined_List
                "\"ID\" TEXT PRIMARY KEY NOT NULL );"); // 1: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEFINEDI_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DefinediInfo entity) {
        stmt.clearBindings();
 
        byte[] defined_List = entity.getDefined_List();
        if (defined_List != null) {
            stmt.bindBlob(1, defined_List);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DefinediInfo entity) {
        stmt.clearBindings();
 
        byte[] defined_List = entity.getDefined_List();
        if (defined_List != null) {
            stmt.bindBlob(1, defined_List);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1);
    }    

    @Override
    public DefinediInfo readEntity(Cursor cursor, int offset) {
        DefinediInfo entity = new DefinediInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0), // defined_List
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DefinediInfo entity, int offset) {
        entity.setDefined_List(cursor.isNull(offset + 0) ? null : cursor.getBlob(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DefinediInfo entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(DefinediInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DefinediInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
