package com.quitter.quitter.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.quitter.quitter.CommonUtils;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table "TAN_WEI_INFO".
 */
@Entity
public class DefinediInfo implements java.io.Serializable {
    private static final long serialVersionUID = -1;

    private byte[] defined_List;

    @Id
    public String id;

    @Transient
    private List<String> definedList;

    @Generated(hash = 994110021)
    public DefinediInfo(byte[] defined_List, String id) {
        this.defined_List = defined_List;
        this.id = id;
    }

    @Generated(hash = 109967126)
    public DefinediInfo() {
    }

    public byte[] getDefined_List() {
        return this.defined_List;
    }

    public void setDefined_List(byte[] defined_List) {
        this.defined_List = defined_List;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS

    public List<String> getDefinedList() {
        if (definedList == null) {
            definedList = CommonUtils.toObject(defined_List);
            if (definedList == null) {
                definedList = new ArrayList<>();
            }
        }
        return definedList;
    }

    public void setDefinedList(List<String> defined) {
        this.definedList = defined;
        this.defined_List = CommonUtils.toByteArray(defined);
    }

}
