package com.quitter.quitter.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.quitter.quitter.CommonUtils;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity mapped to table "TAN_WEI_INFO".
 */
@Entity
public class TanWeiInfo implements java.io.Serializable {
    private static final long serialVersionUID = -1;

    private byte[] tanWeiInfo_List;

    @Id
    public String orderId;

    @Transient
    private List<String> tanWeiInfoList;


    @Generated(hash = 2146657078)
    public TanWeiInfo(byte[] tanWeiInfo_List, String orderId) {
        this.tanWeiInfo_List = tanWeiInfo_List;
        this.orderId = orderId;
    }

    @Generated(hash = 1652152933)
    public TanWeiInfo() {
    }


    public byte[] getTanWeiInfo_List() {
        return this.tanWeiInfo_List;
    }

    public void setTanWeiInfo_List(byte[] tanWeiInfo_List) {
        this.tanWeiInfo_List = tanWeiInfo_List;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public List<String> getTanweiList() {
        if (tanWeiInfoList == null) {
            tanWeiInfoList = CommonUtils.toObject(tanWeiInfo_List);
            if (tanWeiInfoList == null) {
                tanWeiInfoList = new ArrayList<>();
            }
        }
        return tanWeiInfoList;
    }

    public void setTanweiList(List<String> tanWeiInfoList) {
        this.tanWeiInfoList = tanWeiInfoList;
        this.tanWeiInfo_List = CommonUtils.toByteArray(tanWeiInfoList);
    }

    public String getOrderId() {
        return this.orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }


}
